# tasks file for create
- name: Verify required variables are defined
  fail:
    msg: "Variable '{{ item_to_verify }}' is not defined"
  when: item_to_verify not in vars
  with_items: "{{ required_vars_ticket }}"
  loop_control:
    loop_var: item_to_verify

- name: Create temporary file for ticket body
  ansible.builtin.tempfile:
    state: file
    suffix: freshdesk_ticket
  register: ticket_body_file

- name: Create ticket body from template
  ansible.builtin.template:
    src: "{{ template_file_name }}"
    dest: "{{ ticket_body_file.path }}"
  with_items:
    - "{{ template_vars }}"

- name: Create ticket in Freshdesk
  ceradmin.freshdesk.create_ticket:
    recipient: "{{ ticket_recipient }}"
    subject: "{{ ticket_subject }}"
    body: "{{ lookup('file', ticket_body_file.path) }}"
    template_vars: "{{ template_vars }}"
    status: "{{ ticket_status }}"
    ticket_type: Question
    tags: "{{ ticket_tags }}"
    dry_run: "{{ dryrun }}"
  register: details

- name: Print ticket details
  debug:
    msg: "{{ details }}"

- name: Delete temporary file
  ansible.builtin.file:
    path: "{{ ticket_body_file.path }}"
    state: absent

# Register details about the created ticket
# Array, to accommodate this role to be executed in a loop
- name: Register ticket creation result
  ansible.builtin.set_fact:
    ticket_details: "{{ ticket_details|default([]) + [details] }}"
