---
# tasks file for create
- name: Verify required variables are defined
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ required_vars_new_condition_of_use_ticket }}"

- name: Get existing tickets for this allocation from Freshdesk
  ceradmin.freshdesk.get_tickets:
    tags:
      - security
      - auckland
      - "allocation-{{nectar_allocation_id}}"
      - new_condition_of_use
  register: get_tickets_result

- name: Fail if we already have a ticket for this allocation
  fail:
    msg:
      - "A ticket has already been created for allocation {{ nectar_allocation_id }}"
      - "To see it search Freshdesk tickets for tags 'security', 'allocation-{{ nectar_allocation_id }}'"
  when: get_tickets_result.tickets is defined and get_tickets_result.tickets | length > 0

- name: Get allocation details from Nectar allocation API
  ceradmin.nectar_allocation.get_allocation_details:
    allocation_id: "{{ nectar_allocation_id }}"
  register: alloc_details

- name: Get user details from Keystone
  ceradmin.openstack.get_user_by_email:
    email: "{{ alloc_details.allocation.contact_email }}"
  register: user_details

- name: Create temporary file for ticket body
  ansible.builtin.tempfile:
    state: file
    suffix: freshdesk_ticket
  register: ticket_body_file

- name: Create ticket body from template
  ansible.builtin.template:
    src: new_condition_of_use.tpl
    dest: "{{ ticket_body_file.path }}"
  vars:
    first_name: "{{ user_details.user.full_name | split(' ') | first }}"
    project_name: "{{ alloc_details.allocation.project_name }}"

- name: Create ticket in Freshdesk
  ceradmin.freshdesk.create_ticket:
    recipient: "{{ user_details.user.email }}"
    subject: Change in Nectar condition of use
    body: "{{ lookup('file', ticket_body_file.path) }}"
    status: 6
    ticket_type: Question
    tags:
     - security
     - auckland
     - new_condition_of_use
     - "allocation-{{nectar_allocation_id}}"
    dry_run: "{{ dry_run }}"
  register: details

- name: Delete temporary file
  ansible.builtin.file:
    path: "{{ ticket_body_file.path }}"
    state: absent

