fields:
  - id: tenable_host
    type: string
    label: <tenable_host>
    secret: false
  - id: tenable_port
    type: string
    label: <tenable_port>
    secret: false
  - id: tenable_agent_group
    type: string
    label: <tenable_agent_group>
    secret: false
  - id: linking_key
    type: string
    label: <linking_key>
    secret: true
