
- name:  create security group rules
  hosts: localhost  #see ansible_hosts file for configuration
  gather_facts: no
  tasks:

  - openstack.cloud.security_group_rule:
      cloud: openstack
      security_group: foo
      protocol: tcp
      port_range_min: 5895
      port_range_max: 5896
      remote_ip_prefix: 130.216.216.225/32
  
