   
- name:  test security groups
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  gather_facts: no
  roles:
    - openstack_app_creds_ak
    - security_group_info
