---
- name: Collect and set OS properties for active Auckland Nectar servers
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:

  - name: Collect and set OS properties for active Auckland Nectar servers
    ceradmin.openstack.set_servers_os_properties:
    register: details

  - name: Print servers where we couldn't collect any information
    debug:
      msg: "{{ details }}"