- name:  test security groups
  hosts: all
  gather_facts: no
  tasks:
    - openstack.cloud.security_group_info:
        cloud: openstack
        name: ansible_win_ping
        project_id: 0dce37a179dc4f9fa3cc33ff31052fda
      register: sg
      delegate_to: localhost
    
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: sg
        verbosity: 2
      delegate_to: localhost
    
#    - openstack.cloud.security_group_info:
#        cloud: openstack
#        project_id: 0dce37a179dc4f9fa3cc33ff31052fda
#      register: sgs
#
#
#    - name: Print return information from the previous task
#      ansible.builtin.debug:
#        var: sgs
#        verbosity: 2
# 
