---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend:
    - RUN pip3 install --upgrade pip setuptools
  append:
    - RUN alternatives --set python /usr/bin/python3
    - RUN mkdir /nessus_agent_installers
    - COPY NessusAgent* /nessus_agent_installers/

