name: Deploy Infrastructure

on: workflow_call

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    env:
      # Terraform variables
      TF_VAR_os_username: ${{ secrets.OS_USERNAME }}
      TF_VAR_os_password: ${{ secrets.OS_PASSWORD }}
      TF_VAR_os_auth_url: ${{ vars.OS_AUTH_URL }}
      TF_VAR_os_region: ${{ vars.OS_REGION }}
      TF_VAR_os_project_id: ${{ vars.OS_PROJECT_ID }}
      TF_VAR_os_project_name: ${{ vars.OS_PROJECT_NAME }}
      TF_VAR_os_availability_zone: ${{ vars.OS_AVAILABILITY_ZONE }}
      TF_VAR_os_image_id: ${{ vars.OS_IMAGE_ID }}
      TF_VAR_os_flavor_id: ${{ vars.OS_FLAVOR_ID }}
      TF_VAR_os_dns_zone: ${{ vars.OS_DNS_ZONE }}
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialise Terraform
        run: terraform -chdir=infrastructure/ init

      - name : Terraform Plan
        run: terraform -chdir=infrastructure/ plan
