name: Lint all

on: workflow_call

jobs:
  lint_all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: "pip"

      - name: Install dev packages
        run: python -m pip install -r requirements-dev.txt

      - name: YAML code style (yamllint)
        run: python3 -m yamllint -c .yamllint awx

      - name: Install tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: tflint --chdir=infrastructure/
