name: Push and Pull

on:
  push:
    branches:
      - "*"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: "pip"

      - name: Check Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dev packages
        run: python -m pip install -r requirements-dev.txt

      # - name: Python code style (flake8)
      #   run: python3 -m flake8 .

      - name: YAML code style (yamllint)
        run: python3 -m yamllint -c .yamllint awx
